from src.conf.paths import PathConf
from src.util.loaders import load_search_word_cache_handler

search_word_cache_handler = load_search_word_cache_handler(PathConf.jisho_history_word_list_save_path)
search_word_cache_handler.print_cache_summary()